web_app/image_db/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    
    from image_db.main.routes import main
    app.register_blueprint(main)

    return app

web_app/image_db/main/routes.py
from collections import Counter
from flask import Blueprint
from flask import render_template, request
from flask_sqlalchemy import Pagination
from image_db.database.db import Db
from copy import deepcopy as dc

main = Blueprint("main", __name__)

Db()

@main.route("/", methods=["GET"])
@main.route("/home", methods=["GET"])
def home():
    blob_images = Db.getThumbnailContainer().list_blobs()
    count = Counter()
    for image in blob_images:
        blob_client = Db.getThumbnailContainer().get_blob_client(blob=image.name)
        if "tags" in blob_client.get_blob_properties().metadata:
            count.update(
                set(blob_client.get_blob_properties().metadata["tags"].split(", "))
            )

    count = [i[0] for i in count.most_common()]
    all_tags = dc(count)
    all_tags.sort()
    count = count[:15]

    return render_template("home.html", pagination=None, count=count, all_tags=all_tags)


@main.route("/results", methods=["GET", "POST"])
def results():
    page = request.args.get("page", 1, type=int)
    tags = [
        request.args.get("tag1"),
        request.args.get("tag2"),
        request.args.get("tag3"),
    ]
    reduced_tags = set([t for t in tags if t])
    per_page = 9
    blob_images = Db.getThumbnailContainer().list_blobs()
    images = []
    count = Counter()
    for image in blob_images:
        blob_client = Db.getThumbnailContainer().get_blob_client(blob=image.name)
        if "tags" in blob_client.get_blob_properties().metadata:
            image_tags = set(
                blob_client.get_blob_properties().metadata["tags"].split(", ")
            )
            if reduced_tags.issubset(image_tags):
                images.append(blob_client)
                count.update(image_tags)

    count = [i[0] for i in count.most_common()]
    all_tags = dc(count)
    all_tags.sort()
    count = count[:15]
    # get the start and end index based on page number
    start = (page - 1) * per_page
    end = start + per_page
    # page 1 is [0:6], page 2 is [6:12]
    items = images[start:end]
    pagination = Pagination(None, page, per_page, len(images), items)
    return render_template(
        "results.html",
        pagination=pagination,
        count=count,
        all_tags=all_tags,
        tag1=tags[0],
        tag2=tags[1],
        tag3=tags[2],
    )

web_app/image_db/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% endblock content %}

web_app/image_db/templates/layout.html
<!DOCTYPE html>
<html>
{% if title %}
    <title>CLC ImageDB - {{ title }}</title>
{% else %}
    <title>CLC ImageDB</title>
{% endif %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey w3-content" style="max-width:1600px">


<!-- !PAGE CONTENT! -->
<div class="w3-main">

  <!-- Header -->
  <header id="portfolio">
    <div class="w3-container">
      <h1>Image Database</h1>
        <div class="w3-section w3-bottombar w3-padding-16">
            <span class="w3-margin-right">Filter:</span> 

          <form action="{{ url_for('main.results') }}" method="get">            
            <select name="tag1" id="tags">
              <option value=""></option>
              {% for tag in all_tags %}
                {% if tag == tag1 %}
                  <option value={{ tag }} selected>{{ tag }}</option>
                {% else %}
                  <option value={{ tag }}>{{ tag }}</option>
                {% endif %}
              {% endfor %}
            </select> 
            >
             <select name="tag2" id="tags">
              <option value=""></option>
              {% for tag in all_tags %}
                {% if tag == tag2 and tag != tag1 %}
                  <option value={{ tag }} selected>{{ tag }}</option>
                {% elif tag != tag1 %}
                  <option value={{ tag }}>{{ tag }}</option>
                {% endif %}
              {% endfor %}
            </select>   
            >
            <select name="tag3" id="tags">
              <option value=""></option>
              {% for tag in all_tags %}
                {% if tag == tag3 and tag != tag1 and tag != tag2%}
                  <option value={{ tag }} selected>{{ tag }}</option>
                {% elif tag != tag1 and tag != tag2 %}
                  <option value={{ tag }}>{{ tag }}</option>
                {% endif %}
              {% endfor %}
            </select>
            <button class="w3-bar-item w3-black w3-button" type=Submit>GO</button>
            <a href="{{ url_for('main.home') }}" class="w3-bat-item w3-black w3-button">Reset</a>
          </form>    

        </div>
    </div>
  </header>

{% block content %}{% endblock %}
  <!-- Footer -->
  <footer class="w3-container w3-padding-32 w3-dark-grey">
  <div class="w3-row-padding">
    <div class="w3-third">
    </div>

    <div class="w3-third">
      <h3>MOST COMMON TAGS</h3>
      <p>
        {% for tag in count %}
        <span class="w3-tag w3-grey w3-small w3-margin-bottom">{{ tag }}</span>
        {% endfor %}
      </p>
    </div>

  </div>
  </footer>
  
<!-- End page content -->
</div>

</body>
</html>

web_app/image_db/templates/results.html
{% extends "layout.html" %}
{% block content %}

{% if pagination %}
<div class="w3-row-padding">
{% for image in pagination.items%}
      <div class="w3-third w3-container w3-margin-bottom">
        <img src="{{ image.url }}" alt=image style="width:100%" class="w3-hover-opacity">
        <div class="w3-container w3-white">
            <p><b>Tags</b></p>
            <p>{{ image.get_blob_properties().metadata["tags"] }}</p>
        </div>
      </div>
{% endfor %}
      </div>

      <div class="w3-center w3-padding-32">
        <div class="w3-bar">
          {% for page_num in pagination.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if pagination.page == page_num %}
                  <a class="w3-bar-item w3-black w3-button" href="{{ url_for('main.results', page=page_num, tag1=tag1, tag2=tag2, tag3=tag3) }}">{{ page_num }}</a>
                {% else %}
                  <a class="w3-bar-item w3-button w3-hover-black" href="{{ url_for('main.results', page=page_num, tag1=tag1, tag2=tag2, tag3=tag3) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
              <a class="w3-bar-item w3-button w3-hover-black"> ... </a>
            {% endif %}
          {% endfor %}
        </div>
      </div>
{% endif %}
{% endblock content %}